config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount ActionCable.server => '/cable'
  
  root 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'
  get 'terms_of_service', to: 'terms_of_service#show'
  get 'privacy_policy', to: 'privacy_policy#show'

  resources :users, only: %i[new create index show] do
    resource :relationships, only: [:create, :destroy]
  	  get "followings" => "relationships#followings", as: "followings"
  	  get "followers" => "relationships#followers", as: "followers"
    collection do
      get 'search'
    end
  end
  
  resources :test_results do
    collection do
      get 'my_results'
    end
  end

  resource :profile, only: %i[show edit update] 
  resources :password_resets, only: %i[new create edit update]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :test_results, only: %i[index edit update show destroy]
    resources :users, only: %i[index edit update show destroy]
  end

  resources :notifications, only: :index

  resources :rooms
end

app/models/test_result.rb
class TestResult < ApplicationRecord
  belongs_to :user

  validates :test_name, presence: true, length: { maximum: 255 }
  validates :score, presence: true, numericality: { less_than_or_equal_to: :max_score } 
  validates :max_score, presence: true, numericality: { greater_than_or_equal_to: 0 } 
  
  before_save :calculate_achievement_rate

  private

  def calculate_achievement_rate
    return if score.nil? || max_score.nil?
    self.achievement_rate = ((score.to_f / max_score) * 100).round
  end

  def self.user_test_results(user)
    where(user: user).pluck(:test_name, :achievement_rate)
  end
end

app/controllers/admin/test_results_controller.rb
class Admin::TestResultsController < Admin::BaseController
  before_action :find_test_result, only: [:edit, :update, :show, :destroy]

  def index
    @q = TestResult.ransack(params[:q])
    @test_results = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def edit; end

  def update
    if @test_result.update(test_result_params)
      redirect_to admin_test_result_path(@test_result), success: t('defaults.message.updated', item: TestResult.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: TestResult.model_name.human)
      render :edit
    end
  end

  def show; end

  def destroy
    @test_result.destroy!
    redirect_to admin_test_results_path, success: t('defaults.message.deleted', item: TestResult.model_name.human)
  end

  private

  def find_test_result
    @test_result = TestResult.find(params[:id])
  end

  def test_result_params
    params.require(:test_result).permit(:test_name, :score, :max_score)
  end
end

app/controllers/test_results_controller.rb
class TestResultsController < ApplicationController
  before_action :find_test_result, only: [:edit, :update, :destroy]

  def index
    user_ids_to_display = [current_user.id, *current_user.following_ids]
    @user_achievements = User.where(id: user_ids_to_display)
                             .pluck(:id, :nickname)
                             .map { |user_id, nickname| [nickname, TestResult.where(user_id: user_id).average(:achievement_rate).to_f] }
    @test_results = TestResult.where(user_id: user_ids_to_display).order(created_at: :desc).page(params[:page])
  end

  def new
    @test_result = TestResult.new
  end

  def create
    @test_result = current_user.test_results.build(test_result_params)
    if @test_result.save
      redirect_to test_results_path, success: t('defaults.message.created', item: TestResult.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: TestResult.model_name.human)
      render :new
    end
  end

  def show
    @test_result = TestResult.find(params[:id])
  end

  def edit; end

  def update
    if @test_result.update(test_result_params)
      redirect_to @test_result, success: t('defaults.message.updated', item: TestResult.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: TestResult.model_name.human)
      render :edit
    end
  end

  def destroy
    @test_result.destroy!
    redirect_to test_results_path, success: t('defaults.message.deleted', item: TestResult.model_name.human)
  end

  def my_results
    # ログインユーザーだけのテスト結果を取得
    @my_test_results = current_user.test_results.order(created_at: :desc).page(params[:page])
  end

  private

  def find_test_result
    @test_result = current_user.test_results.find(params[:id])
  end

  def test_result_params
    params.require(:test_result).permit(:test_name, :score, :max_score)
  end
end

app/views/admin/test_results/_search_form.html.erb
<%= search_form_for @q, url: admin_test_results_path do |f| %>
  <div class="row">
    <div class="form-inline align-items-center mx-auto">
      <div class="col-auto">
        <%= f.search_field :test_name_cont, class: 'form-control', placeholder: t('defaults.search_word') %>
      </div>
      <div class="col-auto">
        <%= f.date_field :created_at_gteq, class: 'form-control' %>
        <span>〜</span>
        <%= f.date_field :created_at_lteq_end_of_day, class: 'form-control' %>
      </div>
      <div class="col-auto">
        <%= f.submit class: 'btn btn-primary' %>
      </div>
    </div>
  </div>
<% end %>

app/views/admin/test_results/_test_result.html.erb
<tr>
  <td>
    <%= test_result.id %>
  </td>
  <td>
    <%= link_to test_result.test_name, admin_test_result_path(test_result) %>
  </td>
  <td>
    <%= test_result.user.grade_and_class %>
  </td>
  <td>
    <%= test_result.user.decorate.full_name %>
  </td>
  <td>
    <%= l test_result.created_at, format: :long %>
  </td>
  <td>
    <%= link_to t('defaults.show'), admin_test_result_path(test_result), class: 'btn btn-info' %>
    <%= link_to t('defaults.edit'), edit_admin_test_result_path(test_result), class: 'btn btn-success' %>
    <%= link_to t('defaults.delete'), admin_test_result_path(test_result), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/test_results/edit.html.erb
<% content_for(:test_name, @test_result.test_name) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= form_with model: @test_result, url: admin_test_result_path(@test_result), local: true do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <div class="form-group">
          <%= f.label :test_name %>
          <%= f.text_field :test_name, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :score %>
          <%= f.number_field :score, class: 'form-control' %>
        </div>
        <div class="form-group">
          <%= f.label :max_score %>
          <%= f.number_field :max_score, class: 'form-control' %>
        </div>
        <%= f.submit class: 'btn btn-primary' %>
      <% end %>
    </div>
  </div>
</div>

app/views/admin/test_results/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container mb-5 pt-2">
  <h1><%= t('.title') %></h1>
  <div class="row">
    <div class="col-md-12 mb-3">
      <%= render 'search_form' %>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <table class="table table-striped">
        <thead>
        <tr>
          <th scope="col"><%= TestResult.human_attribute_name(:id) %></th>
          <th scope="col"><%= TestResult.human_attribute_name(:test_name) %></th>
          <th scope="col"><%= TestResult.human_attribute_name(:grade_and_class) %></th>
          <th scope="col"><%= TestResult.human_attribute_name(:user) %></th>
          <th scope="col"><%= TestResult.human_attribute_name(:created_at) %></th>
          <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
        <%= render @test_results %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-12">
      <!-- ページネーション -->
      <%= paginate @test_results %>
    </div>
  </div>
</div>

app/views/admin/test_results/show.html.erb
<% content_for(:test_name, @test_result.test_name) %>
<div class="container">
  <div class="row">
    <div class="col-md-10 offset-md-1 col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <div class="text-right mb-3">
        <%= link_to t('defaults.edit'), edit_admin_test_result_path(@test_result), class: 'btn btn-success' %>
        <%= link_to t('defaults.delete'), admin_test_result_path(@test_result), method: :delete, data: { confirm: t('defaults.message.delete_confirm') }, class: 'btn btn-danger' %>
      </div>
      <table class="table table-bordered bg-white">
        <tr>
          <th scope="row"><%= TestResult.human_attribute_name(:id) %></th>
          <td><%= @test_result.id %></td>
        </tr>
        <tr>
          <th scope="row"><%= TestResult.human_attribute_name(:test_name) %></th>
          <td><%= @test_result.test_name %></td>
        </tr>
        <tr>
          <th scope="row"><%= TestResult.human_attribute_name(:user) %></th>
          <td><%= @test_result.user.decorate.full_name %></td>
        </tr>
        <tr>
          <th scope="row"><%= TestResult.human_attribute_name(:score) %></th>
          <td><%= @test_result.score %></td>
        </tr>
        <tr>
          <th scope="row"><%= TestResult.human_attribute_name(:max_score) %></th>
          <td><%= @test_result.max_score %></td>
        </tr>
        <tr>
          <th scope="row"><%= TestResult.human_attribute_name(:achievement_rate) %></th>
          <td><%= @test_result.achievement_rate %></td>
        </tr>
        <tr>
          <th scope="row"><%= TestResult.human_attribute_name(:created_at) %></th>
          <td><%= l @test_result.created_at, format: :long %></td>
        </tr>
      </table>
    </div>
  </div>
</div>