config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount ActionCable.server => '/cable'
  
  root 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'
  get 'terms_of_service', to: 'terms_of_service#show'
  get 'privacy_policy', to: 'privacy_policy#show'

  resources :users, only: %i[new create index show] do
    resource :relationships, only: [:create, :destroy]
  	  get "followings" => "relationships#followings", as: "followings"
  	  get "followers" => "relationships#followers", as: "followers"
    collection do
      get 'search'
    end
  end
  
  resources :test_results do
    collection do
      get 'my_results'
    end
  end

  resource :profile, only: %i[show edit update] 
  resources :password_resets, only: %i[new create edit update]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :test_results, only: %i[index edit update show destroy]
    resources :users, only: %i[index edit update show destroy]
  end

  resources :notifications, only: :index

  resources :rooms
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @user = User.find(params[:user_id])
    current_user.follow(@user)
    @user.create_notification_follow!(current_user)
  end
  
  def destroy
    @user = User.find(params[:user_id])
    current_user.unfollow(@user)
  end
  
  def followings
    user = User.find(params[:user_id])
    @users = user.followings
  end
  
  def followers
    user = User.find(params[:user_id])
    @users = user.followers
  end
end

app/views/relationships/_btn.html.erb
<% if current_user && current_user.id != user.id %>
  <% if current_user.following?(user) %>
    <%= form_tag(user_relationships_path(user), method: :delete, remote: true) do %>
      <%= hidden_field_tag :followed_id, user.id %>
      <%= submit_tag 'フォロー解除', class: 'btn btn-danger btn-block' %>
    <% end %>
  <% else %>
    <%= form_tag(user_relationships_path(user), remote: true) do %>
      <%= hidden_field_tag :followed_id, user.id %>
      <%= submit_tag 'フォローする', class: 'btn btn-primary btn-block' %>
    <% end %>
  <% end %>
<% end %>

app/views/relationships/_follow_button.html.erb
<%= link_to "フォローする", user_relationships_path(user.id), method: :post, remote: true, class: options[:class].presence || "btn btn-success" %>

app/views/relationships/_unfollow_button.html.erb
<%= debug user %>
<%= link_to "フォロー外す", user_relationships_path(user.id), method: :delete, remote: true, class: user_options[:class].presence || "btn btn-info" %>

app/views/relationships/create.js.erb
document.getElementById('follow-ajax-<%= @user.id %>').innerHTML = '<%= j(render partial: 'relationships/btn', locals: { user: @user }).html_safe %>';
document.getElementById('following-count-<%= current_user.id %>').innerHTML = '<%= j(render partial: 'shared/follow_counts', locals: { user: @user }).html_safe %>';

app/views/relationships/destroy.js.erb
document.getElementById('follow-ajax-<%= @user.id %>').innerHTML = '<%= j(render partial: 'relationships/btn', locals: { user: @user }).html_safe %>';
document.getElementById('following-count-<%= current_user.id %>').innerHTML = '<%= j(render partial: 'shared/follow_counts', locals: { user: @user }).html_safe %>';

app/views/relationships/followers.html.erb
<div class="container">
  <h1>フォロワー</h1>
  <% if @users.exists? %>
    <%= render "/users/index", users: @users %>
  <% else %>
    <h3>ユーザーはいません</h3>
  <% end %>
</div>

app/views/relationships/followings.html.erb
<div class="container">
  <h1>フォロー中</h1>
  <% if @users.exists? %>
    <%= render "/users/index", users: @users %>
  <% else %>
    <p>ユーザーはいません</p>
  <% end %>
</div>