config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount ActionCable.server => '/cable'
  
  root 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'
  get 'terms_of_service', to: 'terms_of_service#show'
  get 'privacy_policy', to: 'privacy_policy#show'

  resources :users, only: %i[new create index show] do
    resource :relationships, only: [:create, :destroy]
  	  get "followings" => "relationships#followings", as: "followings"
  	  get "followers" => "relationships#followers", as: "followers"
    collection do
      get 'search'
    end
  end
  
  resources :test_results do
    collection do
      get 'my_results'
    end
  end

  resource :profile, only: %i[show edit update] 
  resources :password_resets, only: %i[new create edit update]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :test_results, only: %i[index edit update show destroy]
    resources :users, only: %i[index edit update show destroy]
  end

  resources :notifications, only: :index

  resources :rooms
end

app/models/test_result.rb
class TestResult < ApplicationRecord
  belongs_to :user

  validates :test_name, presence: true, length: { maximum: 255 }
  validates :score, presence: true, numericality: { less_than_or_equal_to: :max_score } 
  validates :max_score, presence: true, numericality: { greater_than_or_equal_to: 0 } 
  
  before_save :calculate_achievement_rate

  private

  def calculate_achievement_rate
    return if score.nil? || max_score.nil?
    self.achievement_rate = ((score.to_f / max_score) * 100).round
  end

  def self.user_test_results(user)
    where(user: user).pluck(:test_name, :achievement_rate)
  end
end

app/controllers/admin/test_results_controller.rb
class Admin::TestResultsController < Admin::BaseController
  before_action :find_test_result, only: [:edit, :update, :show, :destroy]

  def index
    @q = TestResult.ransack(params[:q])
    @test_results = @q.result(distinct: true).includes(:user).order(created_at: :desc).page(params[:page])
  end

  def edit; end

  def update
    if @test_result.update(test_result_params)
      redirect_to admin_test_result_path(@test_result), success: t('defaults.message.updated', item: TestResult.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: TestResult.model_name.human)
      render :edit
    end
  end

  def show; end

  def destroy
    @test_result.destroy!
    redirect_to admin_test_results_path, success: t('defaults.message.deleted', item: TestResult.model_name.human)
  end

  private

  def find_test_result
    @test_result = TestResult.find(params[:id])
  end

  def test_result_params
    params.require(:test_result).permit(:test_name, :score, :max_score)
  end
end

app/controllers/test_results_controller.rb
class TestResultsController < ApplicationController
  before_action :find_test_result, only: [:edit, :update, :destroy]

  def index
    user_ids_to_display = [current_user.id, *current_user.following_ids]
    @user_achievements = User.where(id: user_ids_to_display)
                             .pluck(:id, :nickname)
                             .map { |user_id, nickname| [nickname, TestResult.where(user_id: user_id).average(:achievement_rate).to_f] }
    @test_results = TestResult.where(user_id: user_ids_to_display).order(created_at: :desc).page(params[:page])
  end

  def new
    @test_result = TestResult.new
  end

  def create
    @test_result = current_user.test_results.build(test_result_params)
    if @test_result.save
      redirect_to test_results_path, success: t('defaults.message.created', item: TestResult.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_created', item: TestResult.model_name.human)
      render :new
    end
  end

  def show
    @test_result = TestResult.find(params[:id])
  end

  def edit; end

  def update
    if @test_result.update(test_result_params)
      redirect_to @test_result, success: t('defaults.message.updated', item: TestResult.model_name.human)
    else
      flash.now['danger'] = t('defaults.message.not_updated', item: TestResult.model_name.human)
      render :edit
    end
  end

  def destroy
    @test_result.destroy!
    redirect_to test_results_path, success: t('defaults.message.deleted', item: TestResult.model_name.human)
  end

  def my_results
    # ログインユーザーだけのテスト結果を取得
    @my_test_results = current_user.test_results.order(created_at: :desc).page(params[:page])
  end

  private

  def find_test_result
    @test_result = current_user.test_results.find(params[:id])
  end

  def test_result_params
    params.require(:test_result).permit(:test_name, :score, :max_score)
  end
end

app/views/test_results/_crud_menus.html.erb
<ul class='crud-menu-btn list-inline float-right'>
  <% if current_user && current_user == test_result.user %>
    <li class="list-inline-item">
      <%= link_to edit_test_result_path(test_result), id: "button-edit-#{test_result.id}" do %>
        <%= icon 'fa', 'pen' %>
      <% end %>
    </li>
    <li class="list-inline-item">
      <%= link_to test_result_path(test_result), id: "button-delete-#{test_result.id}", method: :delete, data: { confirm: t('defaults.message.delete_confirm') } do %>
        <%= icon 'fas', 'trash' %>
      <% end %>
    </li>
  <% end %>
</ul>

app/views/test_results/_form.html.erb
<%= form_with model: test_result, local: true do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="form-group">
    <%= f.label :test_name %>
    <%= f.text_field :test_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :score %>
    <%= f.number_field :score, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :max_score %>
    <%= f.number_field :max_score, class: 'form-control' %>
  </div>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/test_results/_test_result.html.erb
<div class="col-sm-12 col-lg-4 mb-3">
  <div id="test_result-id-<%= test_result.id %>">
    <div class="card">
      <div class="card-body">
        <h4 class="card-title">
          <%= link_to test_result.test_name, test_result_path(test_result) %>
        </h4>
        <%= render 'crud_menus', test_result: test_result if current_user.own?(test_result) %>
        <ul class="list-inline">
          <li class="list-inline-item">
            <%= icon 'far', 'user' %>
            <%= link_to test_result.user.decorate.full_name, user_path(test_result.user) %>
          </li>
          <li class="list-inline-item">
            <%= icon 'far', 'calendar' %>
            <%= l test_result.created_at, format: :long %>
          </li>
        </ul>
        <div>
          <p><strong>点数</strong> <%= test_result.score %></p>
          <p><strong>満点</strong> <%= test_result.max_score %></p>
          <p><strong>達成率</strong> <%= test_result.achievement_rate %>%</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/test_results/edit.html.erb
<% content_for(:test_name, @test_result.test_name) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', { test_result: @test_result } %>
    </div>
  </div>
</div>

app/views/test_results/index.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <h1><%= t '.title' %></h1>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="row">
        <% @test_results.each do |test_result| %>
          <%= render partial: 'test_result', locals: { test_result: test_result } %>
        <% end %>
      </div>
      <%= paginate @test_results %>
      <%= column_chart @user_achievements, xtitle: 'ニックネーム', ytitle: '達成率の平均値', library: { animation: { duration: 1000 }, scales: { y: { beginAtZero: true, max: 100 } } } %>
    </div>
  </div>
</div>

app/views/test_results/my_results.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <h1><%= t '.title' %></h1>
  </div>

  <div class="row">
    <div class="col-12">
      <div class="row">
        <% @my_test_results.each do |test_result| %>
          <%= render partial: 'test_result', locals: { test_result: test_result } %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/test_results/new.html.erb
<% content_for(:title, t('.title')) %>
<div class="container">
  <div class="row">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <%= render 'form', { test_result: @test_result } %>
    </div>
  </div>
</div>

app/views/test_results/show.html.erb
<% content_for(:title, t('.title')) %>
<div class="container pt-5">
  <div class="row mb-3">
    <div class="col-lg-8 offset-lg-2">
      <h1><%= t('.title') %></h1>
      <!-- 掲示板内容 -->
      <article class="card">
        <div class="card-body">
          <h3 class="d-inline"><%= @test_result.test_name%></h3>
          <%= render 'crud_menus', test_result: @test_result %>
          <ul class="list-inline">
            <li class="list-inline-item">by <%= @test_result.user.decorate.full_name %></li>
            <li class="list-inline-item"><%= l @test_result.created_at, format: :long  %></li>
          </ul>
          
          <div class="text-center">
            <p class="lead"><strong>点数:</strong> <%= @test_result.score %></p>
            <p class="lead"><strong>満点:</strong> <%= @test_result.max_score %></p>
            <p class="lead"><strong>達成率:</strong> <%= @test_result.achievement_rate %>%</p>
          </div>
          <%= link_to t('.back_to_index'), test_results_path, class: 'btn btn-primary' %>
        </div>
      </article>
    </div>
  </div>
</div>