config/routes.rb
Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount ActionCable.server => '/cable'
  
  root 'static_pages#top'

  get 'login', to: 'user_sessions#new'
  post 'login', to: 'user_sessions#create'
  get 'logout', to: 'user_sessions#destroy'
  get 'terms_of_service', to: 'terms_of_service#show'
  get 'privacy_policy', to: 'privacy_policy#show'

  resources :users, only: %i[new create index show] do
    resource :relationships, only: [:create, :destroy]
  	  get "followings" => "relationships#followings", as: "followings"
  	  get "followers" => "relationships#followers", as: "followers"
    collection do
      get 'search'
    end
  end
  
  resources :test_results do
    collection do
      get 'my_results'
    end
  end

  resource :profile, only: %i[show edit update] 
  resources :password_resets, only: %i[new create edit update]

  namespace :admin do
    root to: 'dashboards#index'
    get 'login', to: 'user_sessions#new'
    post 'login', to: 'user_sessions#create'
    delete 'logout', to: 'user_sessions#destroy'
    resources :test_results, only: %i[index edit update show destroy]
    resources :users, only: %i[index edit update show destroy]
  end

  resources :notifications, only: :index

  resources :rooms
end

app/views/shared/_before_login_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png' %>
    <% end %>

    <button class='navbar-toggler' data-toggle='collapse' data-target='#navbarSupportedContent' aria-controls='navbarSupportedContent' aria-expanded='false' aria-label='Toggle navigation'>
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item">
          <%= link_to (t 'defaults.login'), login_path ,class: 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>
</header>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_messages" class="alert alert-danger">
    <ul class="mb-0">
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_flash_message.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/shared/_follow_counts.html.erb
<div class="mr-3">
  <div id="following-count-<%= current_user.id %>" class="follow-count">
    <strong>フォロー中:</strong> <%= link_to "#{current_user.followings.count}", user_followings_path(current_user) %>
  </div>
</div>

app/views/shared/_footer.html.erb
<footer id='footer' class="footer-bottom">
  <div class="container">
    <div class="row">
      <div class="col-sm-6 col-12">
        <div class="copyright">
          <p>Test Score Rivals © 2024. Test Score Rivals</p>
        </div>
        <div class="footer-links" >
          <%= link_to '利用規約', terms_of_service_path %> /
          <%= link_to 'プライバシーポリシー', privacy_policy_path %>
        </div>
      </div>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navigation navbar-light bg-light">

    <%= link_to root_path, class: 'navbar-brand' do %>
      <%= image_tag 'logo.png' %>
    <% end %>
    <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav ml-auto main-nav align-items-center">
        <li class="nav-item">
          <%= render 'shared/follow_counts' %>
          <div class="mr-3">
            <strong>フォロワー数:</strong> <%= link_to current_user.followers.count, user_followers_path(current_user) %>
          </div>
        </li>

        <li class="nav-item">
          <%= link_to 'メッセージ一覧', rooms_path, class: 'nav-link' %>
        </li>

        <li class="nav-item">
          <%= link_to 'ユーザー一覧', users_path, class: 'nav-link' %>
        </li>

        <li class="nav-item dropdown dropdown-slide">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= TestResult.model_name.human %>
          </a>

          <div class="dropdown-menu dropdown-menu-right">
            <%= link_to t('test_results.index.title'), test_results_path, class: 'dropdown-item' %>
            <%= link_to t('test_results.new.title'), new_test_result_path, class: 'dropdown-item' %>
          </div>
        </li>

        <li class="nav-item dropdown dropdown-slide">
          <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= '自分の成績' %>
          </a>

          <div class="dropdown-menu dropdown-menu-right">
            <%= link_to t('test_results.my_results.title'), my_results_test_results_path, class: 'dropdown-item' %>
          </div>
        </li>

        <li class="nav-item dropdown dropdown-slide">
          <a href="#" class="nav-link" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="header-profile">
            <%= image_tag current_user.avatar_url, size: '40x40', class: 'rounded-circle mr15'%>
          </a>
          <div class="dropdown-menu dropdown-menu-right">
            <div class="dropdown-item"><%= current_user.decorate.full_name %></div>
            <div class="dropdown-divider"></div>
            <%= link_to (t 'profiles.show.title'), profile_path, class: 'dropdown-item' %>

            <%= link_to (t 'defaults.logout'), logout_path, class: 'dropdown-item' %>
          </div>
        </li>

        <%= link_to(notifications_path) do %>
          <% if unchecked_notifications.any? %>
            <span class="fa-stack">
              <i class="far fa-bell fa-lg fa-stack-2x" style="font-size: 1.5em;"></i>
              <i class="fas fa-circle n-circle fa-stack-1x"></i>
            </span>
          <% else %>
            <i class="far fa-bell fa-lg" style="font-size: 1.5em;"></i>
          <% end %>
        <% end %>
      </ul>
    </div>
  </nav>
</header>